<?php echo $this->getContent(); ?>
<section class="content-header">
    <h1>
        Danh sách album
        <small>Version 1.0</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Danh sách album</li>
    </ol>
</section>
<?php
echo $this->tag->form(
    array(
        "/backend/albums/index",
        "autocomplete" => "off",
        "class" => "form-horizontal",
        "name" => "albumsform",
        "method" => "get"
    )
);
?>
<!-- Main content -->
<section class="content">
    <p><?php echo $this->flash->output() ?></p>
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <a href="/backend/albums/new" class="btn btn-primary">
                                <i class="fa fa-plus-square-o"></i> Tạo mới album
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="row">
                        <div class="col-lg-2">
                            <div class="input-group">
                                <span class="input-group-btn"><button type="submit" class="btn btn-primary btn-flat">
                                        Tìm
                                    </button>
                                  </span>
                                <input type="text" name="filter" id="filter" placeholder="Nhập tên..."
                                       class="form-control" value="<?php echo $data['filter'] ?>">
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <div class="input-group">
                                <span class="input-group-btn"><label class="btn btn-primary btn-flat">
                                        Hiển thị
                                    </label>
                                  </span>
                                <select class="form-control" name="limit">
                                    <?php for ($i = 50; $i <= 100; $i = $i + 50) {
                                        if ($i == $data['limit'])
                                            echo "<option value=\"$i\" selected>$i</option>";
                                        else
                                            echo "<option value=\"$i\">$i</option>";
                                    } ?>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Danh sách album</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="postsdata" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>Tên</th>
                            <th>Ngày tạo</th>
                            <th>Xóa</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($data['data']->items as $item): ?>
                            <tr bgcolor="#a9e5ff">
                                <td><?php echo $item->name ?></td>
                                <td><?php echo DateTime::createFromFormat('YmdHis', $item->datecreate)->format('d/m/Y'); ?></td>
                                <td style="text-align: center" class="albumdel" data-id="<?php echo $item->id ?>">
                                    <a class="delete-btn add-button-disable" href="#" disabled="disabled"><i
                                            class="fa fa-times" id="idalbumdel-<?php echo $item->id ?>"></i></a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <th>Tên</th>
                            <th>Ngày tạo</th>
                            <th>Xóa</th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>
</section>
<?php echo $this->tag->endForm(); ?>
<script async>
    // $(function () {
    //   $("#postsdata").DataTable();
    //});
    var is_loading = false;// Why is working???
    $(document).ready(function () {
        $('#postsdata').dataTable({
            "language": {
                "url": "dataTables.Vietnamese.lang"
            }
        });
        $('.albumdel').off('click').on('click', function (e) {
            e.preventDefault();
            var link = $(this);
            var id = link.data('id');
            if (is_loading == false) {
                is_loading = true;
                $.ajax({
                    url: '/backend/albums/del',
                    type: 'POST',
                    data: {id: id},
                    dataType: 'text',
                    success: function (result) {
                        var show = '#idalbumdel-' + id;
                        $(show).attr("class", result);
                        is_loading = false;
                    }
                });
            }
        });
    });
</script>