<?php echo $this->getContent(); ?>
<section class="content-header">
    <h1>
        Thêm album
        <small>Version 1.0</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Thêm album</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <p><?php echo $this->flash->output() ?></p>
    <div class="row">
        <div class="col-md-6">
            <!-- Horizontal Form -->
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Thông tin album</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form action="/backend/albums/create" class="form-horizontal" method="post" id="albumform" name="albumform">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Tên</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="title" id="title" maxlength="64">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 control-label">Mô tả</label>
                            <div class="col-sm-10">
                                <textarea class="form-control" rows="3" name="description" maxlength="128"></textarea>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <a href="/backend/albums/index" class="btn btn-default">Hủy</a>
                        <button type="submit" class="btn btn-info pull-right" >Lưu</button>
                    </div>
                    <!-- /.box-footer -->
                </form>
            </div>
        </div>
        <!--/.col (right) -->
    </div>
</section>
<script>
    $().ready(function () {
        // validate signup form on keyup and submit
        $("#albumform").validate({
            rules: {
                title: {
                    required: true,
                    minlength: 1
                }
            },
            messages: {
                title: {
                    required: "Nhập tên",
                    minlength: "Tên lớn hơn 1 ký tự"
                }
            }
        });
    });
</script>