<?php echo $this->getContent(); ?>
<section class="content-header">
    <h1>
        Dashboard
        <small>Version 1.0</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <p><?php echo $this->flash->output() ?></p>
    <div class="row">
        <div class="col-md-6">
            <!-- Horizontal Form -->
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">CẤU HÌNH WEBSITE</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form action="/backend/dashboard/saveconfig" class="form-horizontal" method="post" name="webconfig">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Title SEO</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="title" id="title" placeholder="Title SEO" maxlength="64" value="<?php echo $data->title ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 control-label">Description SEO</label>
                            <div class="col-sm-10">
                                <textarea class="form-control" rows="3" name="description" placeholder="Description ..." maxlength="192"><?php echo $data->meta ?></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Tên CTY</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="companyname" id="companyname" placeholder="Tên cty" maxlength="256" value="<?php echo $data->companyname ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Địa chỉ</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="address" id="address" placeholder="Địa chỉ" maxlength="128" value="<?php echo $data->address ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Điện thoại</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="cellphone" id="cellphone" placeholder="Điện thoại" maxlength="20" value="<?php echo $data->cellphone ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="email" id="email" placeholder="Điện thoại" maxlength="20" value="<?php echo $data->email ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Fax</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="fax" id="fax" placeholder="Fax" maxlength="20" value="<?php echo $data->fax ?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Facebook</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="facebook" id="facebook" placeholder="Facebook" maxlength="256" value="<?php echo $data->facebook ?>">
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-info pull-right" >Lưu</button>
                    </div>
                    <!-- /.box-footer -->
                </form>
            </div>
        </div>
        <!--/.col (right) -->
    </div>
</section>