<?php echo $this->getContent(); ?>
<section class="content-header">
    <h1>
        Thư viện hình
        <small>Version 1.0</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Thư viện hình</li>
    </ol>
</section>
<?php
echo $this->tag->form(
    array(
        "/backend/pictures/index",
        "autocomplete" => "off",
        "class" => "form-horizontal",
        "name" => "typespostform",
        "method" => "get"
    )
);
?>

<section class="content">
    <p><?php echo $this->flash->output() ?></p>
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <a href="/backend/pictures/new" class="btn btn-primary">
                                <i class="fa fa-plus-square-o"></i> Thêm hình
                            </a>
                            <a href="/backend/albums/index" class="btn btn-primary">
                                <i class="fa fa-plus-square-o"></i> Danh sách album
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="row">
                        <div class="col-lg-1">
                            <div class="input-group">
                                <span class="input-group-btn"><button type="submit" class="btn btn-primary btn-flat">
                                        Tìm
                                    </button>
                                  </span>
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <div class="input-group">
                                <span class="input-group-btn"><label class="btn btn-primary btn-flat">
                                        Album
                                    </label>
                                  </span>
                                <select class="form-control" name="idalbum">
                                    <option value="">Tất cả</option>
                                    <?php foreach ($data['albums'] as $item) {
                                        if ($item->id == $data['idalbum'])
                                            echo "<option value=\"$item->id\" selected>$item->name</option>";
                                        else
                                            echo "<option value=\"$item->id\">$item->name</option>";
                                    } ?>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <div class="input-group">
                                <span class="input-group-btn"><label class="btn btn-primary btn-flat">
                                        Hiển thị
                                    </label>
                                  </span>
                                <select class="form-control" name="limit">
                                    <?php for ($i = 50; $i <= 100; $i = $i + 50) {
                                        if ($i == $data['limit'])
                                            echo "<option value=\"$i\" selected>$i</option>";
                                        else
                                            echo "<option value=\"$i\">$i</option>";
                                    } ?>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Thư viện hình</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="postsdata" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>Hình</th>
                            <th>Album</th>
                            <th>Đường dẫn</th>
                            <th>Xóa</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($data['data']->items as $item): ?>
                            <tr bgcolor="#a9e5ff">
                                <td>
                                    <img src="<?php echo '\\' . $item->dir; ?>" class="img-rounded"
                                         alt="Cinque Terre" width="200" height="200">
                                </td>
                                <td><?php echo $item->aname ?></td>
                                <td style="text-align: center" width="1000px">
                                    <div class="input-group margin">
                                        <input type="text" class="form-control" readonly
                                               value="<?php echo "http://" . str_replace("\\", "/", $_SERVER['SERVER_NAME'] . "\\" . $item->dir); ?>" >
                                        <span class="input-group-btn">
                                          <button type="button" class="btn btn-info btn-flat">Go!</button>
                                        </span>
                                    </div>
                                </td>
                                <td style="text-align: center" class="picdel" data-id="<?php echo $item->id ?>">
                                    <a class="delete-btn add-button-disable" href="#" disabled="disabled"><i
                                            class="fa fa-times" id="iddel-<?php echo $item->id ?>"></i></a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <th>Hình</th>
                            <th>Album</th>
                            <th>Đường dẫn</th>
                            <th>Xóa</th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>
</section>

<?php echo $this->tag->endForm(); ?>
<script>
    var is_loading = false;// Why is working???
    $(document).ready(function () {
        $('.picdel').off('click').on('click', function (e) {
            e.preventDefault();
            var link = $(this);
            var id = link.data('id');
            if (is_loading == false) {
                is_loading = true;
                $.ajax({
                    url: '/backend/pictures/del',
                    type: 'POST',
                    data: {id: id},
                    dataType: 'text',
                    success: function (result) {
                        var show = '#iddel-' + id;
                        $(show).attr("class", result);
                        is_loading = false;
                    }
                });
            }
        });
    });
</script>