<?php echo $this->getContent(); ?>
<section class="content-header">
    <h1>
        Thêm hình
        <small>Version 1.0</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Thêm hình</li>
    </ol>
</section>
<?php
echo $this->tag->form(
    array(
        "autocomplete" => "off",
        "class" => "form-horizontal",
        "id" => "createPic"
    )
);
?>
<!-- Main content -->
<section class="content">
    <p><?php echo $this->flash->output() ?></p>
    <div class="row">
        <div class="col-md-6">
            <!-- Horizontal Form -->
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Thông tin hình</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                    <div class="box-body">
                        <div class="form-group">
                            <label for="" class="col-sm-3 control-label">Chọn Album</label>
                            <div class="col-sm-9">
                                <select class="form-control" name="albums" id="albums">
                                    <option value="0">Chọn album</option>
                                    <?php foreach ($data as $items): ?>
                                        <?php echo "<option value=\"$items->id\">$items->name</option>" ?>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="" class="col-sm-3 control-label">Up hình</label>
                            <div class="col-sm-9">
                                <div id="fine-uploader-manual-trigger"></div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <a href="/backend/albums/index" class="btn btn-default">Hủy</a>
                    </div>
                    <!-- /.box-footer -->
            </div>
        </div>
        <!--/.col (right) -->
    </div>
</section>
<?php echo $this->tag->endForm(); ?>
<script type="text/template" id="qq-template-manual-trigger">
    <div class="qq-uploader-selector qq-uploader" qq-drop-area-text="Drop files here">
        <div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
            <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"
                 class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
        </div>
        <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
            <span class="qq-upload-drop-area-text-selector"></span>
        </div>
        <div class="buttons">
            <div class="qq-upload-button-selector qq-upload-button">
                <div>Select files</div>
            </div>
            <button type="button" id="trigger-upload" class="btn btn-primary">
                <i class="icon-upload icon-white"></i> Upload
            </button>
        </div>
            <span class="qq-drop-processing-selector qq-drop-processing">
                <span>Processing dropped files...</span>
                <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
            </span>
        <ul class="qq-upload-list-selector qq-upload-list" aria-live="polite" aria-relevant="additions removals">
            <li>
                <div class="qq-progress-bar-container-selector">
                    <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"
                         class="qq-progress-bar-selector qq-progress-bar"></div>
                </div>
                <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
                <img class="qq-thumbnail-selector" qq-max-size="100" qq-server-scale>
                <span class="qq-upload-file-selector qq-upload-file"></span>
                <span class="qq-edit-filename-icon-selector qq-edit-filename-icon" aria-label="Edit filename"></span>
                <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
                <span class="qq-upload-size-selector qq-upload-size"></span>
                <button type="button" class="qq-btn qq-upload-cancel-selector qq-upload-cancel">Cancel</button>
                <button type="button" class="qq-btn qq-upload-retry-selector qq-upload-retry">Retry</button>
                <button type="button" class="qq-btn qq-upload-delete-selector qq-upload-delete">Delete</button>
                <span role="status" class="qq-upload-status-text-selector qq-upload-status-text"></span>
            </li>
        </ul>

        <dialog class="qq-alert-dialog-selector">
            <div class="qq-dialog-message-selector"></div>
            <div class="qq-dialog-buttons">
                <button type="button" class="qq-cancel-button-selector">Close</button>
            </div>
        </dialog>

        <dialog class="qq-confirm-dialog-selector">
            <div class="qq-dialog-message-selector"></div>
            <div class="qq-dialog-buttons">
                <button type="button" class="qq-cancel-button-selector">No</button>
                <button type="button" class="qq-ok-button-selector">Yes</button>
            </div>
        </dialog>

        <dialog class="qq-prompt-dialog-selector">
            <div class="qq-dialog-message-selector"></div>
            <input type="text">
            <div class="qq-dialog-buttons">
                <button type="button" class="qq-cancel-button-selector">Cancel</button>
                <button type="button" class="qq-ok-button-selector">Ok</button>
            </div>
        </dialog>
    </div>
</script>
<style>
    #trigger-upload {
        color: white;
        background-color: #00ABC7;
        font-size: 14px;
        padding: 7px 20px;
        background-image: none;
    }

    #fine-uploader-manual-trigger .qq-upload-button {
        margin-right: 15px;
    }

    #fine-uploader-manual-trigger .buttons {
        width: 36%;
    }

    #fine-uploader-manual-trigger .qq-uploader .qq-total-progress-bar-container {
        width: 60%;
    }
</style>
<script>
    $(document).ready(function () {
        var album = document.getElementById("albums");

        var defaultParams = {
            albumid: document.getElementById("albums").value,
            albumname: $("#albums option:selected").text()
        }
        var manualUploader = new qq.FineUploader({
            element: document.getElementById('fine-uploader-manual-trigger'),
            template: 'qq-template-manual-trigger',
            request: {
                endpoint: 'create',
                params: {
                    albumid: document.getElementById("albums").value,
                    albumname: '0'
                }
            },
            thumbnails: {
                placeholders: {
                    waitingPath: '/img/backend/waiting-generic.png',
                    notAvailablePath: '/img/backend/not_available-generic.png'
                }
            },
            validation: {
                allowedExtensions: ['jpeg', 'jpg', 'gif', 'png'],
                sizeLimit: 5120000, // 50 kB = 50 * 1024 bytes
                itemLimit: 5
            },
            autoUpload: false,
            debug: false,
            callbacks: {
                onSubmit: function (id, fileName) {
                    // Extend the default parameters for all files
                    // with the parameters for _this_ file.
                    // qq.extend is part of a myriad of Fine Uploader
                    // utility functions and cross-browser shims
                    // found in client/js/util.js in the source.
                    var newParams = {
                            albumid: document.getElementById("albums").value,
                            albumname: album.options[album.selectedIndex].text
                        },
                        finalParams = defaultParams;
                    qq.extend(finalParams, newParams);
                    this.setParams(finalParams);
                }
            }
        });
        qq(document.getElementById("trigger-upload")).attach("click", function () {
            manualUploader.uploadStoredFiles();
        });
    });
</script>