<?php echo $this->getContent(); ?>
<section class="content-header">
    <h1>
        Thêm hình
        <small>Version 1.0</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Thêm hình</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <p><?php echo $this->flash->output() ?></p>
    <div class="row">
        <div class="col-md-6">
            <!-- Horizontal Form -->
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Thông tin hình</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form action="/backend/albums/create" class="form-horizontal" method="post" id="albumform" name="albumform">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="" class="col-sm-3 control-label">Nhóm người dùng</label>
                            <div class="col-sm-9">
                                <select class="form-control" name="id_album">
                                    <option value="0">Chọn album</option>
                                    <?php foreach ($data as $items): ?>
                                        <?php echo "<option value=\"$items->id\">$items->name</option>" ?>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <a href="/backend/albums/index" class="btn btn-default">Hủy</a>
                        <button type="submit" class="btn btn-info pull-right" >Lưu</button>
                    </div>
                    <!-- /.box-footer -->
                </form>
            </div>
        </div>
        <!--/.col (right) -->
    </div>
</section>
<script>

</script>