<section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
        <div class="pull-left image">
            <img src="/img/backend/user2-160x160.jpg" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
            <p>Alexander Pierce</p>
            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
    </div>

    </form>
    <!-- /.search form -->
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
        <li>
            <a href="/backend/dashboard/index">
                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
            <span class="pull-right-container">
              <small class="label pull-right bg-green">new</small>
            </span>
            </a>
        </li>
        <li>
            <a href="/backend/users/index">
                <i class="fa fa-users"></i> <span>Quản lý tài khoản</span>
            </a>
        </li>
        <li>
            <a href="/backend/posts/index">
                <i class="fa fa-newspaper-o"></i> <span>Quản lý bài viết</span>
            </a>
        </li>
    </ul>
</section>