<?php echo $this->getContent(); ?>
<section class="content-header">
    <h1>
        Đổi mật khẩu
        <small>Version 1.0</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Đổi mật khẩu</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <p><?php echo $this->flash->output() ?></p>
    <div class="row">
        <div class="col-md-6">
            <!-- Horizontal Form -->
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">ĐỔI MẬT KHẨU</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                <form action="/backend/users/savepass" class="form-horizontal" method="post" id="changepass" name="changepass">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-3 control-label">Mật khẩu cũ</label>
                            <div class="col-sm-9">
                                <input type="password" class="form-control" name="oldpass" id="oldpass"  maxlength="32" value="">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-3 control-label">Mật khẩu mới</label>
                            <div class="col-sm-9">
                                <input type="password" class="form-control" name="newpass" id="newpass" maxlength="32" value="">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-3 control-label">Nhập lại mật khẩu</label>
                            <div class="col-sm-9">
                                <input type="password" class="form-control" name="repass" id="repass" maxlength="32" value="">
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-info pull-right" >Lưu</button>
                    </div>
                    <!-- /.box-footer -->
                </form>
            </div>
        </div>
        <!--/.col (right) -->
    </div>
</section>
<script>
    $().ready(function () {
        // validate signup form on keyup and submit
        $("#changepass").validate({
            rules: {
                oldpass: {
                    required: true,
                    minlength: 6
                },
                newpass: {
                    required: true,
                    minlength: 6
                },
                repass: {
                    required: true,
                    minlength: 5,
                    equalTo: "#newpass"
                }
            },
            messages: {
                oldpass: {
                    required: "Điền tên đăng nhập",
                    minlength: "Tên đăng nhập lớn hơn 5 ký tự"
                },
                newpass: {
                    required: "Nhập mật khẩu",
                    minlength: "Mật khẩu phải lớn hơn 5 ký tự"
                },
                repass: {
                    required: "Nhập lại mật khẩu",
                    minlength: "Mật khẩu phải lớn hơn 5 ký tự",
                    equalTo: "Mật khậu nhập lại không đúng"
                }
            }
        });
    });
</script>