<?php
use  Coredev\Commons\ParamsSEO as params;
?>
<!DOCTYPE HTML>
<html>
<head>
    <?php echo $this->tag->getTitle(); ?>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="description" content="<?php echo params::$meta_description ?>">
    <!--[if lte IE 8]>
    <script src="/assets/js/ie/html5shiv.js"></script><![endif]-->
    <link rel="stylesheet" href="/assets/css/main.css"/>
    <!--[if lte IE 9]>
    <link rel="stylesheet" href="/assets/css/ie9.css"/><![endif]-->
    <!--[if lte IE 8]>
    <link rel="stylesheet" href="/assets/css/ie8.css"/><![endif]-->
    <script src="/assets/js/jquery.min.js"></script>
    <script src="/js/frontend/jquery.validate.min.js"></script>
</head>
<body>
<!-- Wrapper -->
<div id="wrapper">

    <!-- Header -->
    <header id="header">
        <?php $this->partial("share/header"); ?>
    </header>

    <!-- Menu -->
    <nav id="menu">
        <?php $this->partial("share/menu"); ?>
    </nav>

    <!-- Main -->
    <div id="main">
        <?php echo $this->getContent(); ?>
    </div>

    <!-- Footer -->
    <footer id="footer">
        <?php $this->partial("share/footer"); ?>
    </footer>
</div>

<!-- Scripts -->

<script src="/assets/js/skel.min.js"></script>
<script src="/assets/js/util.js"></script>
<!--[if lte IE 8]>
<script src="/assets/js/ie/respond.min.js"></script><![endif]-->
<script src="/assets/js/main.js"></script>

</body>
</html>