<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Quản lý Web</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="/css/backend/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/css/backend/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="/css/backend/ionicons.min.css">
    <!-- jvectormap -->
    <link rel="stylesheet" href="/css/backend/jquery-jvectormap-1.2.2.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/css/backend/AdminLTE.min.css">
    <link rel="stylesheet" href="/css/backend/dataTables.bootstrap.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/css/backend/skins/_all-skins.min.css">
    <script src="/js/backend/jquery-2.2.3.min.js"></script>
    <script src="/js/backend/jquery.validate.min.js"></script>
    <script src="/ckeditor/tinymce.min.js"></script>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">
        <?php $this->partial("share/main_header"); ?>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <?php $this->partial("share/main_sidebar"); ?>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <?php echo $this->getContent(); ?>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b>Version</b> 2.3.5
        </div>
        <strong>Copyright &copy; 2014-2016 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights
        reserved.
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Create the tabs -->
        <?php $this->partial("share/control_sidebar"); ?>
    </aside>
    <!-- /.control-sidebar -->
    <!-- Add the sidebar's background. This div must be placed
         immediately after the control sidebar -->
    <div class="control-sidebar-bg"></div>

</div>
<!-- ./wrapper -->

<!-- jQuery 2.2.3 -->

<!-- Bootstrap 3.3.6 -->
<script src="/js/backend/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="/js/backend/fastclick.min.js"></script>
<!-- AdminLTE App -->
<script src="/js/backend/app.min.js"></script>
<!-- Sparkline -->
<script src="/js/backend/jquery.sparkline.min.js"></script>
<!-- jvectormap -->
<script src="/js/backend/jquery-jvectormap-1.2.2.min.js"></script>
<script src="/js/backend/jquery-jvectormap-world-mill-en.js"></script>
<!-- SlimScroll 1.3.0 -->
<script src="/js/backend/jquery.slimscroll.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/js/backend/demo.js"></script>
<script src="/js/backend/jquery.dataTables.min.js"></script>
<script src="/js/backend/dataTables.bootstrap.min.js"></script>
</body>
</html>
